##회원 가입
#POST http://localhost:8080/user/join
#Content-Type: application/json
#
#{
#    "userId": "test999",
#    "password": "test999",
#    "age": 31,
#    "sex": 0,
#    "emailName": "test@naver.com"
#}
#

###

#인증 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

#인증 로그인 했을 시의  Token 값 사용
GET http://localhost:8080/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTU2NDgxODY2MiwiZXhwIjoxNTY0ODIyMjYyfQ.npeSPII7jE64-gqXiS-gHBsMZDYlj292-ykowck6qMw


###

# 리소스 생성
#POST http://localhost:8080/resources/create
#Content-Type: application/json
#
#[{
#    "name": "/resources/create",
#    "description": "리소스 생성",
#    "authorizationNames": ["ROLE_MANAGER"]
#},{
#    "name": "/authorization/create",
#    "description": "권한 생성",
#    "authorizationNames": ["ROLE_MANAGER"]
#}]

#Create CategoryTest
POST http://localhost:8080/category/create
Content-Type: application/json

{
  "categoryName":"lol",
  "createAt":123434
}

###
